[package]
name = "snake-game"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[lib]
name = "snake_game"
path = "src/lib.rs"

[[bin]]
name = "snake_game"
path = "src/main.rs"

[dependencies]
eframe = "0.27"